app/models/author.py
# app/models/author_sql.py
from app.extensions import db
from app.models.book_author import book_authors

class Author(db.Model):
    __tablename__ = "authors"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    birth_year = db.Column(db.Integer)

    books = db.relationship(
        "Book",
        secondary=book_authors,
        back_populates="authors"
    )

app/models/book.py
# app/models/book_sql.py
from app.extensions import db
from app.models.book_author import book_authors

class Book(db.Model):
    __tablename__ = "books"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    published_year = db.Column(db.Integer)
    isbn = db.Column(db.String, unique=True)
    pages = db.Column(db.Integer)
    language = db.Column(db.String)

    authors = db.relationship(
        "Author",
        secondary=book_authors,
        back_populates="books"
    )

app/models/book_author.py
# app/models/book_author_sql.py
from app.extensions import db

book_authors = db.Table(
    'book_authors',
    db.Column('book_id', db.Integer, db.ForeignKey('books.id'), primary_key=True),
    db.Column('author_id', db.Integer, db.ForeignKey('authors.id'), primary_key=True)
)

app/__init__.py
from flask import Flask
from .extensions import db
from app.routes.routes import routes

def create_app(config_class=None):
    app = Flask(__name__)
    
    if config_class:
        app.config.from_object(config_class)
    
    db.init_app(app)
    
    app.register_blueprint(routes)
    
    return app

def init_db(app):
    with app.app_context():
        db.create_all()

app/routes/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.services.book_author_service import BookAuthorService
from app.services.book_service import BookService
from app.services.author_service import AuthorService
from app.services.population_service import PopulationService

# services
book_service = BookService()
author_service = AuthorService()
library_service = BookAuthorService()
population_service = PopulationService()

routes = Blueprint("routes", __name__, url_prefix="/", template_folder="templates")

@routes.route('/')
def index():
    return render_template("index.html")
#########################
# ----- Book routes -----
#########################
@routes.route('/books/create', methods=['GET', 'POST'])
def create_book():
    if request.method == 'POST':
        title = request.form['title']
        published_year = request.form.get('published_year', None)
        isbn = request.form.get('isbn', None)
        pages = request.form.get('pages', None)
        language = request.form.get('language', None)
        created_book = book_service.create_book(title, published_year, isbn, pages, language)
        return redirect(url_for('routes.view_book', book_id=created_book.id))
    else:
        return render_template("create_book.html")
    
@routes.route('/books/<int:book_id>')
def view_book(book_id):
    book = book_service.get_book_by_id(book_id)
    if not book:
        return "Book not found", 404
    book.authors = library_service.get_authors_for_book(book.id)
    all_authors = author_service.get_all_authors()
    return render_template("view_book.html", book=book, all_authors=all_authors)

@routes.route('/books')
def book_list():
    books = book_service.get_all_books()
    for book in books:
        book.authors = library_service.get_authors_for_book(book.id)
    return render_template("book_list.html", books=books)

@routes.route('/books/<int:book_id>/delete', methods=['POST'])
def delete_book(book_id):
    book_service.delete_book(book_id)
    return redirect(url_for('routes.book_list'))

@routes.route('/books/<int:book_id>/edit', methods=['GET', 'POST'])
def edit_book(book_id):
    book = book_service.get_book_by_id(book_id)
    if not book:
        return "Book not found", 404
    if request.method == 'POST':
        book.title = request.form['title']
        book.published_year = request.form.get('published_year', None)
        book.isbn = request.form.get('isbn', None)
        book.pages = request.form.get('pages', None)
        book.language = request.form.get('language', None)
        book_service.update_book(book)
        return redirect(url_for('routes.view_book', book_id=book.id))
    else:
        return render_template("edit_book.html", book=book)
    
##########################
# ---- Author routes -----
##########################
@routes.route('/authors/create', methods=['GET', 'POST'])
def create_author():
    if request.method == 'POST':
        name = request.form['name']
        birth_year = request.form.get('birth_year', None)
        created_author = author_service.create_author(name, birth_year)
        return redirect(url_for('routes.view_author', author_id=created_author.id))
    else:
        return render_template("create_author.html")
    
@routes.route('/authors/<int:author_id>')
def view_author(author_id):
    author = author_service.get_author_by_id(author_id)
    if not author:
        return "Author not found", 404
    author.books = library_service.get_books_for_author(author.id)
    all_books = book_service.get_all_books()
    return render_template("view_author.html", author=author, all_books=all_books)

@routes.route('/authors')
def author_list():
    authors = author_service.get_all_authors()
    for author in authors:
        author.books = library_service.get_books_for_author(author.id)
    return render_template("author_list.html", authors=authors)

@routes.route('/authors/<int:author_id>/delete', methods=['POST'])
def delete_author(author_id):
    author_service.delete_author(author_id)
    return redirect(url_for('routes.author_list'))

@routes.route('/authors/<int:author_id>/edit', methods=['GET', 'POST'])
def edit_author(author_id):
    author = author_service.get_author_by_id(author_id)
    if not author:
        return "Author not found", 404
    if request.method == 'POST':
        author.name = request.form['name']
        author.birth_year = request.form.get('birth_year', None)
        author_service.update_author(author)
        return redirect(url_for('routes.view_author', author_id=author.id))
    else:
        return render_template("edit_author.html", author=author)
    
###########################
# -- Book-Author routes -----
###########################

# attach books to authors
@routes.route('/authors/link', methods=['GET', 'POST'])
def link_author_book():
    if request.method == 'POST':
        book_id = int(request.form['book_id'])
        author_id = int(request.form['author_id'])
        library_service.add_author_to_book(book_id, author_id)
        return redirect(url_for('routes.book_list'))
    else:
        # quesionable routesroach with a larger database
        books = book_service.get_all_books()
        authors = author_service.get_all_authors()
        return render_template("link_author_book.html", books=books, authors=authors)
# remove author from book

@routes.route('/authors/remove', methods=['GET', 'POST'])
def remove_author_book():
    if request.method == 'POST':
        book_id = int(request.form['book_id'])
        author_id = int(request.form['author_id'])
        library_service.remove_author_from_book(book_id, author_id)
        return redirect(url_for('routes.book_list'))
    else:
        books = book_service.get_all_books()
        authors = author_service.get_all_authors()
        return render_template("remove_author_book.html", books=books, authors=authors)

app/templates/author_list.html
{% extends "layout.html" %} {% block content %}
<section>
  <h2>Authors</h2>
  {% for author in authors %}
  <ul>
    <li>
      <p><strong>{{ author.name }}</strong></p>

      <p>
        <!-- if any books take title of each -->
        Books: {% if author.books %} {{ author.books | map(attribute='title') |
        join(', ') }} {% else %}
        <em>No books</em>
        {% endif %}
      </p>

      <p>
        Birth Year: {% if author.birth_year %}{{ author.birth_year }}{% else
        %}<em>N/A</em>{% endif %}
      </p>

      <a href="{{ url_for('routes.edit_author', author_id=author.id) }}"
        >&#9998; Edit</a
      >
    </li>
  </ul>
  {% endfor %}
</section>
{% endblock %}

app/templates/book_list.html
{% extends 'layout.html' %} {% block content %}
<section>
  <h2>Books</h2>
  {% for book in books %}

  <ul>
    <li>
      <p>
        <strong>{{ book.title }}</strong>
        ( {% if book.published_year %} {{ book.published_year }} {% else %}
        <em>Unknown Year</em>
        {% endif %} )
      </p>

      <p>
        ISBN: {% if book.isbn %} {{ book.isbn }} {% else %}
        <em>N/A</em>
        {% endif %}
      </p>

      <p>
        Pages: {% if book.pages %} {{ book.pages }} {% else %}
        <em>N/A</em>
        {% endif %}
      </p>

      <p>
        Language: {% if book.language %} {{ book.language }} {% else %}
        <em>N/A</em>
        {% endif %}
      </p>

      <p>
        Authors: {% if book.authors %} {{ book.authors | map(attribute='name') |
        join(', ') }} {% else %}
        <em>No authors</em>
        {% endif %}
      </p>

      <a href="{{ url_for('routes.edit_book', book_id=book.id) }}"
        >&#9998; Edit</a
      >
    </li>
  </ul>
  {% endfor %}
</section>
{% endblock %}

app/templates/create_author.html
{% extends "layout.html" %} {% block content %}
<section>
  <h2>Create Author</h2>
  <form method="POST" action="{{ url_for('routes.create_author') }}">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name="name" required />

    <label for="birth_year">Birth Year</label>
    <input type="number" id="birth_year" name="birth_year" required />

    <button type="submit" class="btn btn-primary">Create Author</button>
  </form>
</section>
{% endblock %}

app/templates/create_book.html
{% extends "layout.html" %} {% block content %}
<section>
  <h2>Register Book</h2>
  <form method="POST" action="{{ url_for('routes.create_book') }}">
    <label for="title">Title</label>
    <input type="text" id="title" name="title" required />

    <label for="published_year">Published Year</label>
    <input type="number" id="published_year" name="published_year" />

    <label for="isbn">ISBN</label>
    <input type="text" id="isbn" name="isbn" />

    <label for="pages">Pages</label>
    <input type="number" id="pages" name="pages" />

    <label for="language">Language</label>
    <input type="text" id="language" name="language" />

    <input type="submit" value="Create Book" />
  </form>
</section>
{% endblock %}

app/templates/edit_author.html
{% extends "layout.html" %} {% block content %}
<section>
  <h2>Edit Author</h2>
  <form
    method="POST"
    action="{{ url_for('routes.edit_author', author_id=author.id)}}"
  >
    <label for="name">Name</label>
    <input
      type="text"
      class="form-control"
      id="name"
      name="name"
      value="{{ author.name }}"
      required
    />

    <label for="birth_year">Birth Year</label>
    <input
      type="number"
      id="birth_year"
      name="birth_year"
      value="{{ author.birth_year }}"
    />

    <button type="submit" class="btn btn-primary">Save Changes</button>
  </form>

  <form
    method="POST"
    action="{{ url_for('routes.delete_author', author_id=author.id) }}"
  >
    <button type="submit" class="btn-delete">&#9003; Delete</button>
  </form>
</section>
{% endblock %}

app/templates/edit_book.html
{% extends "layout.html" %} {% block content %}
<section>
  <h2>Edit Book</h2>
  <form method="POST">
    <label for="title">Title</label>
    <input
      type="text"
      id="title"
      name="title"
      value="{{ book.title }}"
      required
    />

    <label for="published_year">Published Year:</label>
    <input
      type="number"
      id="published_year"
      name="published_year"
      value="{{ book.published_year }}"
    />

    <label for="isbn">ISBN</label>
    <input type="text" id="isbn" name="isbn" value="{{ book.isbn }}" />

    <label for="pages">Pages</label>
    <input type="number" id="pages" name="pages" value="{{ book.pages }}" />

    <label for="language">Language</label>
    <input
      type="text"
      id="language"
      name="language"
      value="{{ book.language }}"
    />

    <input type="submit" value="Save Changes" />
  </form>

  <form
    method="POST"
    action="{{ url_for('routes.delete_book', book_id=book.id) }}"
  >
    <button type="submit" class="btn-delete">&#9003; Delete</button>
  </form>
</section>
{% endblock %}

app/templates/index.html
{% extends "layout.html" %} {% block content %}
<section>
  <img
    src="./static/rat-dance.gif"
    alt="Computer man"
    style="width: 128px; height: 128px"
  />
  <h2>Welcome to the Library</h2>
  <p>Use the navigation bar to manage books and authors.</p>
</section>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Python Library</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
    <nav>
      <a href="{{ url_for('routes.index') }}">Home</a> |
      <a href="{{ url_for('routes.create_book') }}">Add Book</a> |
      <a href="{{ url_for('routes.create_author') }}">Add Author</a> |
      <a href="{{ url_for('routes.author_list') }}">Authors</a> |
      <a href="{{ url_for('routes.book_list') }}">Books</a> |
      <a href="{{ url_for('routes.link_author_book') }}">Link Author to Book</a
      >|
      <a href="{{ url_for('routes.remove_author_book') }}"
        >Remove Author from Book</a
      >
    </nav>
  </head>
  <body>
    <header>
      <h1>Python Library</h1>
    </header>

    <body>
      {% block content %}{% endblock %}
    </body>

    <footer>
      <p>&copy; 2025 Python Library</p>
    </footer>
  </body>
</html>

app/templates/link_author_book.html
{% extends "layout.html" %} {% block content %}
<section>
  <h2>Link Author to Book</h2>
  <form method="POST" action="{{ url_for('routes.link_author_book') }}">
    <label for="book_id">Select Book:</label>
    <select name="book_id" id="book_id" required>
      {% for book in books %}
      <option value="{{ book.id }}">{{ book.title }}</option>
      {% endfor %}
    </select>

    <label for="author_id">Select Author:</label>
    <select name="author_id" id="author_id" required>
      {% for author in authors %}
      <option value="{{ author.id }}">{{ author.name }}</option>
      {% endfor %}
    </select>

    <button type="submit">Link Author to Book</button>
  </form>
</section>
{% endblock %}

app/templates/remove_author_book.html
{% extends "layout.html" %} {% block content %}
<section>
  <h2>Remove Author from Book</h2>
  <form method="POST" action="{{ url_for('routes.remove_author_book') }}">
    <label for="book_id">Select Book:</label>
    <select name="book_id" id="book_id" required>
      {% for book in books %}
      <option value="{{ book.id }}">{{ book.title }}</option>
      {% endfor %}
    </select>

    <label for="author_id">Select Author:</label>
    <select name="author_id" id="author_id" required>
      {% for author in authors %}
      <option value="{{ author.id }}">{{ author.name }}</option>
      {% endfor %}
    </select>

    <button type="submit" class="btn-delete">Remove Author from Book</button>
  </form>
</section>
{% endblock %}

app/templates/view_author.html
{% extends 'layout.html' %} {% block content %}
<section>
  <h2>Author Details</h2>
  <ul>
    <li>
      <p><strong>{{ author.name }}</strong></p>
      <p>
        Books: {% if author.books %} {{ author.books | map(attribute='title') |
        join(', ') }} {% else %}
        <em>No books</em>
        {% endif %}
      </p>
      <p>Birth Year: {{ author.birth_year or "N/A" }}</p>
      <p>
        <a href="{{ url_for('routes.edit_author', author_id=author.id) }}"
          >&#9998; Edit</a
        >
      </p>
      <a href="{{ url_for('routes.author_list') }}">&#8592; Back to Authors</a>
    </li>
  </ul>
</section>
{% endblock %}

app/templates/view_book.html
{% extends 'layout.html' %} {% block content %}
<section>
  <h2>Book Details</h2>
  <ul>
    <li>
      <p>
        <strong>{{ book.title }}</strong> ({{ book.published_year or "Unknown
        Year" }})
      </p>
      <p>ISBN: {{ book.isbn or "N/A" }}</p>
      <p>Pages: {{ book.pages or "N/A" }}</p>
      <p>Language: {{ book.language or "N/A" }}</p>
      <p>
        Authors: {% if book.authors %} {{ book.authors | map(attribute='name') |
        join(', ') }} {% else %} No authors {% endif %}
      </p>
      <p>
        <a href="{{ url_for('routes.edit_book', book_id=book.id) }}"
          >&#9998; Edit</a
        >
      </p>
      <p>
        <a href="{{ url_for('routes.book_list') }}">&#8592; Back to Books</a>
      </p>
    </li>
  </ul>
</section>
{% endblock %}